version: "3.9"
services:
  ss-server:
    image: shadowsocks/shadowsocks-libev
    ports:
      - 8080:8388
      - 8080:8388/udp
    environment:
      - PASSWORD=password
  nginx-server:
    image: nginx
    volumes:
      - ./nginx-server.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:8388
      - 8081:8388/udp
    depends_on:
      - ss-server